@colors=("red"."green","blue");
@colors=qw(red green blue);
print"@colors\n";
print"@colors[0]\n";
print"@colors[-1]\n";
@names=qw(John Jane Alice Bob);
print"Total:",scalar@names."\n";
@months=qw(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec);
print"@months[5..7]\n";
splice(@months,2,2);
print"@months\n";
$string1="perl,pyhton,ruby";
@arr2=split(",",$string1);
print"@arr2\n";
@words=qw(This is perl);
$str=join(" ",@words);
print"$str\n";
$comString="car,plane,bike,ship";
@vehicle=split(",",$comString);
print"@vehicle\n";
$newStr=join("|",@vehicle);
print"$newStr\n";
@numbers=(9,2,5,1,3);
@sorted=sort(@numbers);
print"@sorted\n";
@merged=(@numbers,@sorted);
print"@merged\n";
@fruits=qw(apple banana);
push(@fruits,orange);
print"@fruits\n";
pop(@fruits);
print"@fruits\n";
unshift(@fruits,kiwi);
print"@fruits\n";
shift(@fruits);
print"@fruits\n";